# This workflow will install Python dependencies and run tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Test

on:
  push:
    branches: [ master, test ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: [3.9, "3.11"]


    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Restore engines
      id: cache-temp-restore
      uses: actions/cache/restore@v3
      with:
        path: |
          TEMP
        key: ${{ matrix.os }}-engines
    - name: Stored
      if: steps.cache-temp-restore.outputs.cache-hit != 'true'
      run: echo "FAIL"
    - name: Test with pytest
      id: pytest
      run: |
        pytest --log-cli-level=10
    - name: Used
      if: steps.pytest.outputs.used != '1'
      run: |
        echo "${{steps.pytest.outputs.used}}"
        echo "FAIL2"
    - name: Save engines
      id: cache-temp-save
      uses: actions/cache/save@v3
      with:
        path: |
          TEMP
        key: ${{ steps.cache-temp-restore.outputs.cache-primary-key }}
